### ISSUE TITLE
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://eodhistoricaldata.com/api/historical-market-cap/AAPL.US?fmt=json&api_token=APIKEY&from=2020-01-01

### ISSUE THREAD

**Issue by Travis-Barton** [LautaroParada/eod-data#39]
```
from eod import EodHistoricalData
# create the instance of the SDK
api_key = 'MY API KEY'
client = EodHistoricalData(api_key)
resp = client.get_market_cap(symbol='AAPL.US', from_='2020-01-01')
```

returns the error:

```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/forecasting/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/opt/anaconda3/envs/forecasting/lib/python3.10/site-packages/eod/fundamental_economic_data/historical_market_capitalization_api/market_capitalization.py", line 34, in get_market_cap
    return super().handle_request(self.endpoint, query_params) 
  File "/opt/anaconda3/envs/forecasting/lib/python3.10/site-packages/eod/request_handler_class/request_handler.py", line 40, in handle_request
    self.resp.raise_for_status()
  File "/opt/anaconda3/envs/forecasting/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://eodhistoricaldata.com/api/historical-market-cap/AAPL.US?fmt=json&api_token=(MYAPIKEYTHATIMHIDING)&from=2020-01-01

```

any idea why? 

Edit: It seems to have used all 20 of my requests, but I only ran it once. does the internals run a series of queries?

**Comment by LautaroParada** [comment]
Hi Travis, thank you for opening this issue. The client doesn't do any internal runs; it only takes the URL and requests the data from the API. The error you displayed shows a [403 error](https://www.hostinger.com/tutorials/what-is-403-forbidden-error-and-how-to-fix-it); **This is a client-side error**. Most likely, your API key doesn't have access to that portion of the API (remember that are different tiers).

In my opinion, you should upgrade your plan in order to have the data.
